apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myargocd
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/IsaSubhi/ArgoCD_Project.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: myappargocd-ns
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
